version: "3.9"
services:
  pantry-tracker-db:
    image: postgres
    restart: always
    container_name: nodemailerRabbit
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: 18er0821
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest   
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres:
